[package]
name = "pixela"
version = "0.1.0"
edition = "2021"
authors = ["ladicle"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
dirs = "4.0.0"
